### ISSUE TITLE
New Synapse Module API support

### ISSUE THREAD

**Issue by spantaleev** [digitalentity/matrix_encryption_disabler#1]
Can this module be ported to the new Synapse Module API: https://matrix-org.github.io/synapse/v1.52/modules/index.html

People will then be able to register it under `modules` in `homeserver.yaml`, and not under `third_party_event_rules`.

I'd like to add support for this to [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) and it'd be much easier if we can just inject it into the `modules` list, as opposed to defining `third_party_event_rules` which only seems to support just one filtering module.

**Comment by digitalentity** [comment]
Here you are. Thanks for pointing out the new Module API!
